-- Migration: 0001_create_mandates_table.sql
-- Phase 1: Create the mandates table matching the Mandate TypeScript interface.
--
-- Run this via the Supabase dashboard SQL editor, or with:
--   supabase db push
--
-- Nested TypeScript objects are flattened into prefixed columns
-- (e.g. scope.merchant_allowlist → scope_merchant_allowlist).
-- This avoids JSONB columns so that each field is individually queryable
-- and constrained at the database level.
--
-- The `daily_spent` column is provisioned here for Phase 2 cap enforcement.
-- No application logic touches it yet.

CREATE TABLE IF NOT EXISTS mandates (
  -- Primary key: generated by the application (issueMandate), not by the DB.
  mandate_id          UUID          PRIMARY KEY,

  -- Agent / principal identity
  agent_id            TEXT          NOT NULL,
  principal_id        TEXT          NOT NULL,

  -- scope (flattened from MandateScope)
  scope_merchant_allowlist  TEXT[]  NOT NULL DEFAULT '{}',
  scope_category_allowlist  TEXT[]  NOT NULL DEFAULT '{}',

  -- limits (flattened from MandateLimits)
  -- Stored as NUMERIC to avoid floating-point rounding on paise amounts.
  limits_max_per_txn  NUMERIC       NOT NULL CHECK (limits_max_per_txn > 0),
  limits_daily_cap    NUMERIC       NOT NULL CHECK (limits_daily_cap > 0),
  limits_currency     TEXT          NOT NULL DEFAULT 'INR',

  -- validity (flattened from MandateValidity)
  validity_not_before TIMESTAMPTZ   NOT NULL,
  validity_not_after  TIMESTAMPTZ   NOT NULL,
  CONSTRAINT validity_window_check CHECK (validity_not_after > validity_not_before),

  -- Other mandate fields
  confirmation_threshold  NUMERIC   NOT NULL CHECK (confirmation_threshold >= 0),

  -- Unique nonce — prevents mandate replay.
  -- Even if all other fields are identical, distinct nonces make each mandate unique.
  nonce               TEXT          NOT NULL UNIQUE,

  -- Lifecycle status. Must match the MandateStatus TypeScript union.
  status              TEXT          NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'expired', 'revoked', 'exhausted')),

  -- Ed25519 signature (base64) over the canonical JSON of all other fields.
  signature           TEXT          NOT NULL,

  -- ── Phase 2 column ─────────────────────────────────────────────────────
  -- Running total of paise spent today against this mandate's daily_cap.
  -- Updated atomically by the gate enforcement logic in Phase 2.
  -- Resets at the start of each calendar day (UTC) — reset logic in Phase 2.
  daily_spent         NUMERIC       NOT NULL DEFAULT 0
                        CHECK (daily_spent >= 0),

  -- ── Timestamps ──────────────────────────────────────────────────────────
  created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ── Indexes ─────────────────────────────────────────────────────────────────

-- Common lookup: which mandates belong to a given agent?
CREATE INDEX IF NOT EXISTS idx_mandates_agent_id
  ON mandates (agent_id);

-- Common lookup: which mandates belong to a given principal?
CREATE INDEX IF NOT EXISTS idx_mandates_principal_id
  ON mandates (principal_id);

-- Status filter: gate queries will typically filter by status = 'active'.
CREATE INDEX IF NOT EXISTS idx_mandates_status
  ON mandates (status);

-- ── Row Level Security ───────────────────────────────────────────────────────
-- RLS is enabled so that only the service_role key (used server-side) has access.
-- The Supabase service_role key bypasses RLS entirely — no explicit policy is
-- needed to allow server-side access.
--
-- Consequence: the anon key and any authenticated user key are DENIED all access
-- to this table until explicit policies are added in Phase 2. This is the most
-- secure default: deny everything, add permissions as needed.
ALTER TABLE mandates ENABLE ROW LEVEL SECURITY;

-- ── Auto-update timestamp trigger ───────────────────────────────────────────
-- Creates (or replaces) a function and trigger to keep `updated_at` current
-- whenever a row is modified. Supabase does not do this automatically.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER mandates_updated_at
  BEFORE UPDATE ON mandates
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
