import { describe, it, expect } from "vitest";
import { generateMandateKeyPair } from "../keys";
import { issueMandate } from "../sign";
import { verifyMandateSignature } from "../verify";
import { canonicalize } from "../canonicalize";
import type { Mandate, MandateInput, UnsignedMandate } from "../types";

// ---------------------------------------------------------------------------
// Shared test fixture
// ---------------------------------------------------------------------------

/** A minimal valid MandateInput used across multiple tests. */
const SAMPLE_INPUT: MandateInput = {
  agent_id: "agent-test-001",
  principal_id: "principal-human-001",
  scope: {
    merchant_allowlist: ["merchant_abc", "merchant_xyz"],
    category_allowlist: ["TRAVEL", "SaaS"],
  },
  limits: {
    max_per_txn: 50_000,   // ₹500 in paise
    daily_cap: 200_000,    // ₹2,000 in paise
    currency: "INR",
  },
  validity: {
    not_before: "2026-01-01T00:00:00Z",
    not_after: "2026-12-31T23:59:59Z",
  },
  confirmation_threshold: 100_000, // ₹1,000 in paise
};

// ---------------------------------------------------------------------------
// 1. Happy path: a validly issued mandate verifies successfully
// ---------------------------------------------------------------------------

describe("issueMandate + verifyMandateSignature (happy path)", () => {
  it("verifies a freshly issued mandate", () => {
    const { publicKey, privateKey } = generateMandateKeyPair();
    const mandate = issueMandate(SAMPLE_INPUT, privateKey);

    expect(verifyMandateSignature(mandate, publicKey)).toBe(true);
  });

  it("issued mandate contains all expected fields", () => {
    const { privateKey } = generateMandateKeyPair();
    const mandate = issueMandate(SAMPLE_INPUT, privateKey);

    // Envelope fields generated by issueMandate
    expect(mandate.mandate_id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
    expect(mandate.nonce).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
    expect(mandate.status).toBe("active");
    expect(typeof mandate.signature).toBe("string");
    expect(mandate.signature.length).toBeGreaterThan(0);

    // Input fields passed through unchanged
    expect(mandate.agent_id).toBe(SAMPLE_INPUT.agent_id);
    expect(mandate.principal_id).toBe(SAMPLE_INPUT.principal_id);
    expect(mandate.limits.max_per_txn).toBe(SAMPLE_INPUT.limits.max_per_txn);
    expect(mandate.limits.currency).toBe("INR");
  });
});

// ---------------------------------------------------------------------------
// 2. Tamper detection: mutating ANY field must cause verification to fail
// ---------------------------------------------------------------------------

describe("tamper detection", () => {
  // Generate once for this describe block to keep tests fast.
  const keys = generateMandateKeyPair();
  const publicKey = keys.publicKey;
  const mandate = issueMandate(SAMPLE_INPUT, keys.privateKey);

  const cases: Array<[string, Mandate]> = [
    [
      "agent_id changed",
      { ...mandate, agent_id: "tampered-agent" },
    ],
    [
      "principal_id changed",
      { ...mandate, principal_id: "tampered-principal" },
    ],
    [
      "limits.max_per_txn bumped",
      { ...mandate, limits: { ...mandate.limits, max_per_txn: 999_999_999 } },
    ],
    [
      "limits.daily_cap bumped",
      { ...mandate, limits: { ...mandate.limits, daily_cap: 999_999_999 } },
    ],
    [
      "limits.currency changed",
      { ...mandate, limits: { ...mandate.limits, currency: "USD" } },
    ],
    [
      "scope.merchant_allowlist widened",
      {
        ...mandate,
        scope: {
          ...mandate.scope,
          merchant_allowlist: ["merchant_abc", "merchant_xyz", "merchant_evil"],
        },
      },
    ],
    [
      "scope.category_allowlist widened",
      {
        ...mandate,
        scope: {
          ...mandate.scope,
          category_allowlist: ["TRAVEL", "SaaS", "GAMBLING"],
        },
      },
    ],
    [
      "validity.not_after extended",
      {
        ...mandate,
        validity: { ...mandate.validity, not_after: "2099-12-31T23:59:59Z" },
      },
    ],
    [
      "validity.not_before moved earlier",
      {
        ...mandate,
        validity: { ...mandate.validity, not_before: "2000-01-01T00:00:00Z" },
      },
    ],
    [
      "confirmation_threshold lowered",
      { ...mandate, confirmation_threshold: 1 },
    ],
    [
      "status forged to active (on a different mandate)",
      { ...mandate, status: "revoked" as const },
    ],
    [
      "nonce swapped",
      { ...mandate, nonce: "00000000-0000-4000-8000-000000000000" },
    ],
    [
      "mandate_id swapped",
      { ...mandate, mandate_id: "00000000-0000-4000-8000-000000000000" },
    ],
    [
      "signature directly mutated",
      { ...mandate, signature: mandate.signature.split("").reverse().join("") },
    ],
  ];

  it.each(cases)("fails when %s", (_label, tampered) => {
    expect(verifyMandateSignature(tampered, publicKey)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 3. Malformed input: must return false, never throw
// ---------------------------------------------------------------------------

describe("verifyMandateSignature with malformed input", () => {
  const keys = generateMandateKeyPair();
  const publicKey = keys.publicKey;
  const mandate = issueMandate(SAMPLE_INPUT, keys.privateKey);

  it("returns false for a garbage signature string", () => {
    expect(
      verifyMandateSignature({ ...mandate, signature: "not-valid-base64!!!" }, publicKey),
    ).toBe(false);
  });

  it("returns false for an empty signature", () => {
    expect(
      verifyMandateSignature({ ...mandate, signature: "" }, publicKey),
    ).toBe(false);
  });

  it("returns false for a random 88-char base64 string as signature", () => {
    const garbage = Buffer.alloc(64, 0xff).toString("base64");
    expect(
      verifyMandateSignature({ ...mandate, signature: garbage }, publicKey),
    ).toBe(false);
  });

  it("returns false for an invalid public key", () => {
    expect(
      verifyMandateSignature(mandate, "not-a-real-key"),
    ).toBe(false);
  });

  it("returns false for an empty public key", () => {
    expect(verifyMandateSignature(mandate, "")).toBe(false);
  });

  it("returns false for a public key from a different keypair", () => {
    const { publicKey: otherPublicKey } = generateMandateKeyPair();
    expect(verifyMandateSignature(mandate, otherPublicKey)).toBe(false);
  });

  it("does not throw when mandate fields are missing (untrusted input)", () => {
    // Cast to Mandate to simulate deserialized untrusted JSON missing a field.
    const partial = { ...mandate, limits: undefined } as unknown as Mandate;
    expect(() => verifyMandateSignature(partial, publicKey)).not.toThrow();
    expect(verifyMandateSignature(partial, publicKey)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 4. Uniqueness: identical inputs yield different mandate_id and nonce
// ---------------------------------------------------------------------------

describe("mandate uniqueness", () => {
  it("two mandates with identical input have different mandate_ids and nonces", () => {
    const { privateKey } = generateMandateKeyPair();
    const a = issueMandate(SAMPLE_INPUT, privateKey);
    const b = issueMandate(SAMPLE_INPUT, privateKey);

    expect(a.mandate_id).not.toBe(b.mandate_id);
    expect(a.nonce).not.toBe(b.nonce);
    // Different nonces → different canonical JSON → different signatures
    expect(a.signature).not.toBe(b.signature);
  });

  it("mandate_id and nonce are never the same value within a single mandate", () => {
    const { privateKey } = generateMandateKeyPair();
    const mandate = issueMandate(SAMPLE_INPUT, privateKey);
    expect(mandate.mandate_id).not.toBe(mandate.nonce);
  });
});

// ---------------------------------------------------------------------------
// 5. Canonicalisation: stable regardless of input key order
// ---------------------------------------------------------------------------

describe("canonicalize", () => {
  it("produces identical output regardless of object key insertion order", () => {
    const baseUnsigned: UnsignedMandate = {
      mandate_id: "test-id",
      agent_id: "agent-1",
      principal_id: "principal-1",
      scope: {
        merchant_allowlist: ["m1"],
        category_allowlist: ["c1"],
      },
      limits: {
        max_per_txn: 1000,
        daily_cap: 5000,
        currency: "INR",
      },
      validity: {
        not_before: "2026-01-01T00:00:00Z",
        not_after: "2026-12-31T23:59:59Z",
      },
      confirmation_threshold: 2000,
      nonce: "test-nonce",
      status: "active",
    };

    // Construct the same mandate with keys inserted in a different order.
    const reordered: UnsignedMandate = {
      status: baseUnsigned.status,
      nonce: baseUnsigned.nonce,
      confirmation_threshold: baseUnsigned.confirmation_threshold,
      validity: {
        not_after: baseUnsigned.validity.not_after,
        not_before: baseUnsigned.validity.not_before,
      },
      limits: {
        currency: baseUnsigned.limits.currency,
        daily_cap: baseUnsigned.limits.daily_cap,
        max_per_txn: baseUnsigned.limits.max_per_txn,
      },
      scope: {
        category_allowlist: baseUnsigned.scope.category_allowlist,
        merchant_allowlist: baseUnsigned.scope.merchant_allowlist,
      },
      principal_id: baseUnsigned.principal_id,
      agent_id: baseUnsigned.agent_id,
      mandate_id: baseUnsigned.mandate_id,
    };

    expect(canonicalize(baseUnsigned)).toBe(canonicalize(reordered));
  });

  it("does NOT sort array elements (array order is significant)", () => {
    const make = (merchants: string[]): UnsignedMandate => ({
      mandate_id: "id",
      agent_id: "a",
      principal_id: "p",
      scope: { merchant_allowlist: merchants, category_allowlist: [] },
      limits: { max_per_txn: 1, daily_cap: 1, currency: "INR" },
      validity: { not_before: "2026-01-01T00:00:00Z", not_after: "2026-12-31T23:59:59Z" },
      confirmation_threshold: 1,
      nonce: "n",
      status: "active",
    });

    // ["a","b"] and ["b","a"] are different arrays — canonical output must differ.
    expect(canonicalize(make(["a", "b"]))).not.toBe(canonicalize(make(["b", "a"])));
  });

  it("produces compact JSON (no extra whitespace)", () => {
    const unsigned: UnsignedMandate = {
      mandate_id: "id",
      agent_id: "a",
      principal_id: "p",
      scope: { merchant_allowlist: [], category_allowlist: [] },
      limits: { max_per_txn: 1, daily_cap: 1, currency: "INR" },
      validity: { not_before: "2026-01-01T00:00:00Z", not_after: "2026-12-31T23:59:59Z" },
      confirmation_threshold: 1,
      nonce: "n",
      status: "active",
    };
    const result = canonicalize(unsigned);
    expect(result).not.toContain("  "); // no double spaces
    expect(result).not.toMatch(/:\s/);  // no ": " spacing
  });
});
